project_id = "pcsancednuywpxvuruqb"

[functions.ivs-stream]
verify_jwt = false

[functions.aws-media]
verify_jwt = false

[functions.create-payment]
verify_jwt = true

[functions.create-payout]
verify_jwt = true

[functions.payment-webhook]
verify_jwt = false

[functions.customer-support]
verify_jwt = false

[functions.validate-referral]
verify_jwt = false

[functions.get-maps-key]
verify_jwt = false

[functions.calculate-courier-rate]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.storage-upload]
verify_jwt = false
